title: EV paradox # Change this to your book title.
author: Groep C5 # Change this to your name (or your team/organization name).
copyright: "2025"
logo: images/favicon.png

# Force re-execution of notebooks on each build.
execute:
  execute_notebooks: force
  timeout: 300  # Increase timeout for complex plots
  allow_errors: false
  stderr_output: show

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/TygoHonig/InfoVisualization2025.git
  path_to_book: docs
  branch: main

# Add Github buttons to your book
html:
  favicon: images/favicon.png
  use_issues_button: true
  use_repository_button: true
  show_toggle_button: true

# Add launch buttons
launch_buttons:
  binderhub_url: ""
  colab_url: "https://colab.research.google.com"
  jupyterhub_url: ""

parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - html_admonition
    - html_image

sphinx:
  extra_extensions:
    - "IPython.sphinxext.ipython_console_highlighting"
  config:
    html_theme_options:
      use_download_button: true
      use_fullscreen_button: true
    # Allow raw HTML in notebooks
    nbsphinx_allow_errors: true
    nb_output_stderr: "show"