# -- Basisinstellingen --------------------------------------------------
title: "De Grote Elektrische Paradox"
author: "Groep 12  –  InfoVis 2025"
copyright: "2025"
logo: ../images/favicon.png       # of weglaten

# -- Bouwinstellingen ---------------------------------------------------
repository:
  url: https://github.com/TygoHonig/InfoVisualization2025
  path_to_book: docs
  branch: main

execute:
  execute_notebooks: force

sphinx:
  extra_extensions:
    - sphinx.ext.autosectionlabel

# ------------------ Presentatie ------------------
html:
  show_toggle_button: false   # geen 'show/hide code' knop
  copybutton: true            # laat wel copy-icoontje bij code-output

sphinx:
  config:
    nb_hide_code: true        # verberg álle cel-inputs
sphinx:
  config:
    html_js_files:
      - https://cdn.plot.ly/plotly-latest.min.js
